### ISSUE TITLE
Unable to use with Xcode 10 (Swift 4.1.50)

### ISSUE THREAD

**Issue by majd** [Touch-Tech-Payments/3DS-iOS#10]
Please provide an updated version that's compiled with Swift 4.1.50. Otherwise, Xcode 10 throws the error ```Module compiled with Swift 4.1 cannot be imported in Swift 4.1.50``` and is unable to compile.

**Comment by majd** [comment]
@daveparsons1 Any updates on this?

**Comment by daveparsons1** [comment]
Hi @majd, I have only got around to looking at this this week. XCode 10's new build system is causing a few problems, but I hope to get a working version by the end of the week.

Its Swift 4.2 now, correct?

**Comment by majd** [comment]
Yes, it's Swift 4.2 currently. But it could still be compiled with Swift 4.1, you'll just have to recompile it with Xcode 10 since it uses Swift 4.1.5 instead of 4.1. But if you can get it updated for Swift 4.2, that's even better. :)

The actual problem is that modules compiled with Swift 4.1 can't be imported into Swift 4.1.5 modules (and vice versa).

**Comment by daveparsons1** [comment]
@majd version 1.2 should be available now on cocoapods trunk, our own specs repo and as a [release](https://github.com/Touch-Tech-Payments/3DS-iOS/releases/tag/v1.2.0). 😃

**Comment by majd** [comment]
@daveparsons1 I was able to get the newer version of the library to compile but now experiencing this issue on runtime as soon as the app tries to load the frameworks/libraries. Could be that you're linking against an older outdated version of libswiftFoundation.dylib. Could you please look into it? 😄 
 
```
dyld: Symbol not found: _$S10Foundation13CustomNSErrorP11errorDomainSSvgZTj
  Referenced from: /Users/***/Library/Developer/CoreSimulator/Devices/09630894-579B-4592-AA01-077619CBFE8E/data/Containers/Bundle/Application/C18E9A9C-0AA3-40B3-8583-A51CDFD1A541/***.app/Frameworks/TTPaymentsOTP.framework/TTPaymentsOTP
  Expected in: /Users/***/Library/Developer/CoreSimulator/Devices/09630894-579B-4592-AA01-077619CBFE8E/data/Containers/Bundle/Application/C18E9A9C-0AA3-40B3-8583-A51CDFD1A541/***.app/Frameworks/libswiftFoundation.dylib
 in /Users/***/Library/Developer/CoreSimulator/Devices/09630894-579B-4592-AA01-077619CBFE8E/data/Containers/Bundle/Application/C18E9A9C-0AA3-40B3-8583-A51CDFD1A541/***.app/Frameworks/TTPaymentsOTP.framework/TTPaymentsOTP
```

**Comment by daveparsons1** [comment]
I'll have a look

**Comment by daveparsons1** [comment]
@majd version 1.2.1 should fix the issue. :)
