### ISSUE TITLE
Compile with swift 5.1.2

### ISSUE THREAD

**Issue by JanC** [Touch-Tech-Payments/3DS-iOS#17]
Hi,
your latest `1.4.0` release is compiled with Swift 5.1 but now the stable swift version that comes with XCode 11.2 is 5.1.2 which yields 

```
import TTPaymentsOTP Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: 
```

Could you please recompile and make a new release? You could also consider setting the `BUILD_LIBRARY_FOR_DISTRIBUTION` to benefit from the module stability as explained in the WWDC 2019 [Binary Frameworks in Swift session](https://developer.apple.com/videos/play/wwdc2019/416/)

**Comment by JanC** [comment]
@daveparsons1 is this somehow planned? Recompiling the `1.4.0` release with XCode 11.2  should be straightforward.

**Comment by JanC** [comment]
hey @daveparsons1 
I see that you have just compiled and release a version for Swift 5.3.

However, we'd like to use Xcode 11.5 now that comes with Swift 5.2.x and for that you don't provide the binary.

> Module compiled with Swift 5.3 cannot be imported by the Swift 5.2.4 

Have you considered using the `BUILD_LIBRARY_FOR_DISTRIBUTION` when compiling as suggested? That could save you quite some work :) 

cheers

**Comment by daveparsons1** [comment]
Hi @JanC , oh sorry, I was told to update it for the XCode 12 beta and Swift 5.3.
I released it early to try and unblock you, with the ambition to release a version later this week with a Swift Module interface via the `BUILD_LIBRARY_FOR_DISTRIBUTION`.

I might make a release specifically for Swift 5.2.4, to unblock you, as it will be quicker...

Thanks for flagging

**Comment by daveparsons1** [comment]
Hey @JanC , I added [v1.5.1](https://github.com/Touch-Tech-Payments/3DS-iOS/releases/tag/v1.5.1). Updating Cocoapods trunk and our own specs repo now.

Please let me know if you have any issues. I will be working towards building a framework with swift module stability for most of the remainder of the week. Hopefully that will be the last update :)

Dave

**Comment by JanC** [comment]
> Hey @JanC , I added v1.5.1. Updating Cocoapods trunk and our own specs repo now.

nice! thanks a lot, that indeed allows us to switch to XC 11.5. I've just tested it and it compiles fine.

> I will be working towards building a framework with swift module stability for most of the remainder of the week. Hopefully that will be the last update :)

Very much appreciated 👍
