### ISSUE TITLE
Incompatibility with Xcode 12.2 - Swift 5.3.1 

### ISSUE THREAD

**Issue by fssilva** [Touch-Tech-Payments/3DS-iOS#23]
Hi,

Is there a plan to support Xcode 12.2 with swift 5.3.1 or provide a version that's ABI stable ? The latest version 1.6.1 is not compatible with the latest Xcode.

![Screenshot 2020-11-12 at 13 37 50](https://user-images.githubusercontent.com/589306/99565377-d6932700-29cb-11eb-8c7d-d77a2b160e31.png)

Thanks in advance.

**Comment by fssilva** [comment]
@daveparsons1 Do you know if an update will be possible ?

**Comment by daveparsons1** [comment]
Hi @fssilva , can you please contact your N26 account manager for Touchtech so that this work can be added via normal channels and scheduled accordingly.
